on: [push] # push 代码时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tencent Cloudbase Github Action Example
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # 使用云开发 Github Action 部署
      - name: publish blog to tencent static site
        working-directory: ./public
        shell: bash
        run: |
          tcb login --apiKeyId ${{ secrets.SECRETID }} --apiKey ${{ secrets.SECRETKEY }}
          tcb hosting deploy ./ -e ${{ secrets.ENVID }}