name: Deploy to Tencent CloudBase

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Hexo Souce Repo to Tencent CloudBase
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      # NPM and Hexo
      - name: NPM
        run: npm install
      # Deploy static to Tencent CloudBase
      - name: publish blog to tencent static site
        working-directory: ./public
        shell: bash
        run: |
          tcb login --apiKeyId ${{ secrets.SECRETID }} --apiKey ${{ secrets.SECRETKEY }}
          tcb hosting deploy ./ -e ${{ secrets.ENVID }}
