name: Deploy to Tencent CloudBase

on: push

jobs:
  build:
    name: Deploy cayzlh.com
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [13.x]

    steps:

      - name: Checkout self
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}


      - name: Install dependencies.
        run: |
          npm i -g @cloudbase/cli
          npm install hexo-cli -g
          npm install


      - name: Deploy Github page.
        run: |
          hexo clean
          hexo g
          hexo d

      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v1.1.1
        with:
          secretId: ${{ secrets.SECRETID }}
          secretKey: ${{ secrets.SECRETKEY }}
          envId: ${{ secrets.ENVID }}
          staticSrcPath: public